version: "3"

volumes:
  db_data:
services:
  armory-db:
    container_name: armory-db
    image: postgres
    # restart: always
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      APP_ENV: ${APP_ENV}
      POSTGRES_USER: postgres
      POSTGRES_DB: gwdb
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - source: db_password
    healthcheck:
      test: pg_isready -U postgres
    networks:
      - gw-network

  backend:
    container_name: backend 
    build:
      context: ./backend
    working_dir: /usr/src/app
    depends_on:
      armory-db:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
    environment:
      APP_ENV: ${APP_ENV}
      GIN_MODE: debug
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - source: db_password
    networks:
      - gw-network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        CONFIG_FILE: "localopensslnginx"
    # restart: always
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./frontend/dist:/var/www/frontend-dist-dev:ro
      - ./local-certs/certs:/etc/nginx/certs:ro
    networks:
      - gw-network
    depends_on:
      - armory-db
      - backend
  

networks:
  gw-network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt