version: "3"

volumes:
  db_data:
services:
  armory-db:
    container_name: armory-db
    image: postgres
    restart: unless-stopped
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: gwdb
      POSTGRES_PASSWORD_FILE: /run/secrets/armory_db_password
    secrets:
      - source: armory_db_password
    healthcheck:
      test: pg_isready -U postgres
    networks:
      - armory-network

  armory:
    container_name: armory 
    restart: unless-stopped
    build:
      context: ./backend
    working_dir: /usr/src/app
    depends_on:
      armory-db:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV}
      GIN_MODE: debug
      ARMORY_DB_PASSWORD_FILE: /run/secrets/armory_db_password
    secrets:
      - source: armory_db_password
    networks:
      - armory-network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        CONFIG_FILE: "localopensslnginx"
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./frontend/dist:/var/www/frontend-dist-dev:ro
      - ./local-certs/certs:/etc/nginx/certs:ro
    networks:
      - armory-network
    depends_on:
      - armory-db
      - armory
  

networks:
  armory-network:
    driver: bridge

secrets:
  armory_db_password:
    file: ./secrets/armory_db_password.txt